inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
